In [1]:
# Import the data science package `NumPy` as `np`
import numpy as np

# DS109-09 - Notes - Numpy


## DS109-09-02 - NumPy Arrays

In [2]:
# create an array
my_first_array = np.array([7,2,1])

In [3]:
# call the array
my_first_array

array([7, 2, 1])

In [4]:
# print the array
print(my_first_array)

[7 2 1]


---
## DS109-09-03 - Aggregate Functions on Arrays

In [5]:
# find the max value in the array
my_first_array.max()

7

In [6]:
# find the minimum value in the array
my_first_array.min()

1

In [7]:
# find the mean of the array
my_first_array.mean()

3.3333333333333335

In [8]:
# find the standard deviation of the array
my_first_array.std()

2.6246692913372702

In [9]:
# find the sum of the array
my_first_array.sum()

10

---
## DS109-09-04 - Data Generation with NumPy

In [10]:
# generate an array with named `RandomNumbers` that is only 1 digit long
RandomNumbers = np.random.random(1)

In [11]:
# call the array to output it
RandomNumbers

array([0.32704722])

In [12]:
# generate an array of all 1's
allOnes = np.ones(7)

In [13]:
# output the array
allOnes

array([1., 1., 1., 1., 1., 1., 1.])

In [14]:
# generate an array of all 0's
allZeros = np.zeros(2)

In [15]:
# output the array
allZeros

array([0., 0.])

---

## DS109-09-05 - Arithmetic with Arrays

In [17]:
my_second_array = np.array([1,2,7])

### Adding

In [18]:
# The result is a 3rd array where
# every number is the su of the 1st and 2nd array
my_first_array + my_second_array

array([8, 4, 8])

In [19]:
# Assigning the resulting array to a variable
ArraySummed = my_first_array + my_second_array

In [20]:
# Call the variable to output
ArraySummed

array([8, 4, 8])

### Subtracting

In [21]:
# Subtract the 2nd array from the 1st array
ArraySubtracted = my_first_array - my_second_array

In [22]:
# Call the variable to output
ArraySubtracted

array([ 6,  0, -6])

### Multiplying

In [24]:
# Mutiplying the 2 arrays
ArrayMultiplied = my_first_array * my_second_array

In [25]:
# Call the variable to output
ArrayMultiplied

array([7, 4, 7])

### Dividing

In [26]:
# Divide the arrays
ArrayDivided = my_first_array / my_second_array

In [27]:
# Call the variable to output
ArrayDivided

array([7.        , 1.        , 0.14285714])

---
## Arithmetic on an Array

### Multiplying

In [28]:
# Multiply the array by 4
TimesFour = my_first_array * 4

In [29]:
# Call to output
TimesFour

array([28,  8,  4])

### Dividing

In [30]:
# Divide the array by 4
DividedFour = my_first_array / 4

In [31]:
# Call to output
DividedFour

array([1.75, 0.5 , 0.25])

### Adding

In [32]:
# Add 4 to every number in the array
PlusFour = my_first_array + 4

In [33]:
# Call to output
PlusFour

array([11,  6,  5])

### Subtracting

In [34]:
# Subtract 4 from every number
MinusFour = my_first_array - 4

In [35]:
# Call to output
MinusFour

array([ 3, -2, -3])

---
## DS109-09-06 - Indexing on Arrays

In [37]:
# call the array
my_first_array

array([7, 2, 1])

In [38]:
# Get the first place item in the array
my_first_array[0]

7

### Accessing multiple numbers in an array

In [39]:
# Access everything in the current array
my_first_array[0:3]

array([7, 2, 1])

In [40]:
# When you want everything after index position (here index 1)
my_first_array[1:]

array([2, 1])

---
## DS109-09-07 - Creating Matrices with Arrays

In [41]:
# Make a matrix out of arrays by listing them separated by comma
my_first_matrix = np.array([[8,9], [5,4]])

In [42]:
# call the new matrix
my_first_matrix

array([[8, 9],
       [5, 4]])

### Matrix of all 1s

In [43]:
# Create a matrix filled with ones, 7 rows by 2 columns
AllOnesMatrix = np.ones((7,2))

In [44]:
# call the new matrix
AllOnesMatrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Matrix of all 0s

In [45]:
# create a matrix of 0s
AllZerosMatrix = np.zeros((7,2))

In [46]:
# call the new matrix
AllZerosMatrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Random Matrix

In [47]:
# create a matrix random numbers
RandomMatrix = np.random.random((7,2))

In [48]:
# call the new matrix
RandomMatrix

array([[0.10049432, 0.16144798],
       [0.65019041, 0.61006861],
       [0.20943249, 0.27021337],
       [0.6038384 , 0.29365857],
       [0.93799553, 0.87735896],
       [0.53369877, 0.61493779],
       [0.95410618, 0.87647426]])

---
## DS109-09-08 - Matrix Arithmetic and Aggregation

### Arithmetic

In [49]:
# Add the randomly generated matrix and other matrix
RandomMatrix + AllOnesMatrix

array([[1.10049432, 1.16144798],
       [1.65019041, 1.61006861],
       [1.20943249, 1.27021337],
       [1.6038384 , 1.29365857],
       [1.93799553, 1.87735896],
       [1.53369877, 1.61493779],
       [1.95410618, 1.87647426]])

### Aggregation

In [50]:
# Call the aggregation functions on a matrix too
my_first_matrix.min()

4

In [53]:
my_first_matrix.max()

9

In [54]:
my_first_matrix.sum()

26

In [55]:
my_first_matrix.mean()

6.5

In [56]:
my_first_matrix.std()

2.0615528128088303

---
## DS109-09-09 - Matrix Indexing

In [57]:
# Access the `9` in the `my_first_matrix`
my_first_matrix[0,1]

9

---
## DS109-09-10 - Aggregating Matrix Values Across Columns and Rows

In [59]:
# Find the largest number in the COLUMNS
my_first_matrix.max(axis=0)

array([8, 9])

In [60]:
# Find the largest numbers in the ROWS
my_first_matrix.max(axis=1)

array([9, 5])

---
## DS109-09-11 - Manipulating Matrics
### Transposing

In [61]:
# The AllOnesMatrix before transposing
AllOnesMatrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
# Transpose the AllOnesMatrix
AllOnesMatrix.T

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### Reshaping

In [63]:
# Reshape this matrix to a single column with 14 rows
AllOnesMatrix.reshape(14,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])