#### Heather Walker - 2022-09-28
# DS109-09-13 - Arrays and Matrices Hands-On
---
#### Directions
For your Hands-On, you will be practicing your new skills with arrays and matrices! This Hands-On **will** be graded, so be sure you complete all requirements. The best way to become a data scientist is to practice!
</br></br>
Please complete the following tasks in a Jupyter Notebook file, using the `numpy` package:

---

In [1]:
# import NumPy to start
import numpy as np

---
### 1. Create a five element array using your favorite numbers named `myFavorites`. 

In [2]:
myFavorites = np.array([2,3,5,12,22])

---
### 2. Perform each of the five aggregate functions on your array.
.max()
.min()
.mean()
.std()
.sum()

In [3]:
# .max()
myFavorites.max()

22

In [4]:
# .min()
myFavorites.min()

2

In [5]:
# .mean()
myFavorites.mean()

8.8

In [6]:
# .std()
myFavorites.std()

7.467261881037788

In [7]:
# .sum()
myFavorites.sum()

44

---
### 3. Create a five element array containing only ones named `OneArrayToRuleThemAll`.

In [8]:
# use `.ones()` to create a matrix of ones
OneArrayToRuleThemAll = np.ones(5)

In [9]:
# call to output
OneArrayToRuleThemAll

array([1., 1., 1., 1., 1.])

---
### 4.  Add `myFavorites` and `OneArrayToRuleThemAll`.

In [10]:
# add the 2 arrays and assign result to variable
ArraySummed = myFavorites + OneArrayToRuleThemAll

In [11]:
# call to output
ArraySummed

array([ 3.,  4.,  6., 13., 23.])

---
### 5.  Multiply every element in myFavorites by two.

In [12]:
# multiply myFavorites by 2 and assign result to variable
MultiplyBy2 = myFavorites * 2

In [13]:
# call to output
MultiplyBy2

array([ 4,  6, 10, 24, 44])

---
### 6.  Call the third element in `myFavorites` using indexing.

In [14]:
# call the 3rd element or [2] in `myFavorites`
myFavorites[2]

5

---
### 7. Create a four element, two-by-two matrix of numbers named `TheMatrixHasYou`.

In [15]:
# create a 2x2 matrix
TheMatrixHasYou = np.random.random((2,2))

In [16]:
# call to output
TheMatrixHasYou

array([[0.05473249, 0.16981207],
       [0.05157497, 0.64880269]])

---
### 8.  Access the upper left element in `TheMatrixHasYou` using indexing.

In [17]:
# acces the upper left element or row 0, column 0
TheMatrixHasYou[0,0]

0.054732492867833216

---
### 9.  Find the largest number in each row for `TheMatrixHasYou`.

In [18]:
# use `.max()` and `axis=1' to specify ROWS
TheMatrixHasYou.max(axis=1)

array([0.16981207, 0.64880269])

---
### 10. Reshape `TheMatrixHasYou` into a matrix with one row and four columns.

In [19]:
# use `.reshape()`
TheMatrixHasYou.reshape(4,1)

array([[0.05473249],
       [0.16981207],
       [0.05157497],
       [0.64880269]])